# Generated by Django 2.0.5 on 2018-05-17 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('sub1_m', models.IntegerField()),
                ('sub2_m', models.IntegerField()),
                ('sub3_m', models.IntegerField()),
            ],
        ),
    ]
